### ISSUE TITLE
Console logs in code

### ISSUE THREAD

**Issue by AdelRizq** [fuboki10/Ketofan-Back-End#20]
## Some console logs were forgotten to remove after debugging in the home page, the doctor request page, and maybe on some other pages 
<br />

<div align="center">

![image](https://user-images.githubusercontent.com/40351413/122104918-79077180-ce18-11eb-9052-0975a8373892.png)
<br />

![image](https://user-images.githubusercontent.com/40351413/122104353-e1098800-ce17-11eb-8768-7f9b7e1d74fd.png)

</div>

**Comment by fuboki10** [comment]
I will open an issue in the front-end repo.
Thank You.
